name: CI

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm install

            - name: Run ESLint
              run: npm run lint

            - name: Run Prettier check
              run: npm run format:check

    build:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies
              run: |
                  npm install
                  cd client && npm install
                  cd ../server && npm install

            - name: Build client
              run: cd client && npm run build

            - name: Build Docker image
              run: docker build -t py-editor:test .
